import type { TimelineEntry } from './types';

export const timeline: TimelineEntry[] = [
  { id: 'black-mountain', era: 'Before Season 1', title: 'Ryn withdraws to Black Mountain', summary: 'The feared Despicable Heretic abandons the wider martial world and lives as a hermit, farmer, and unwilling local legend.', importance: 'Character' },
  { id: 'lucy-arrives', era: 'Season 1', title: 'Lucy climbs the wrong mountain', summary: 'Fleeing assassins, Princess Lucy meets Ryn without knowing his identity and begins living at his remote cabin.', importance: 'Arc' },
  { id: 'five-sect-order', era: 'Season 2', title: 'The Five-Sect arrest order resurfaces', summary: 'Lucy learns why the Orthodox world calls Ryn a villain and begins uncovering the missing context behind his crimes.', importance: 'World' },
  { id: 'capital-coup', era: 'Season 3', title: 'The imperial coup fails', summary: 'Lucy proves herself as a political strategist and leader while Ryn ends the violence only when civilians are threatened.', importance: 'World' },
  { id: 'unrankable', era: 'Season 4', title: 'Ryn appears above Rank #1', summary: 'The Heavenly Register briefly lists Ryn without a number and labels him UNRANKABLE, throwing the martial world into panic.', importance: 'World' },
  { id: 'trial-home', era: 'Season 5', title: 'Trial, home, and first kiss', summary: 'Lucy defends Ryn without pretending he shares Orthodox values. He builds her a room, she calls Black Mountain home, and their slow-burn finally becomes mutual.', importance: 'Character' },
  { id: 'taewon-arrives', era: 'Season 6', title: 'Rank #1 comes to tea', summary: 'First Sovereign Seo Taewon measures Ryn, accepts that no meaningful comparison exists, and becomes an unlikely ally while Ryn and Lucy become an actual couple.', importance: 'Arc' },
  { id: 'wei-cang', era: 'Season 7', title: 'Lucy defeats the Smiling Archivist', summary: 'Lucy exposes Wei Cang’s manufactured-war network through investigation and information strategy, revealing the ancient name Hollow Heaven.', importance: 'World' },
  { id: 'marriage-treaty', era: 'Season 8', title: 'Lucy refuses to become treaty currency', summary: 'A northern political marriage crisis is resolved through diplomacy and trade reform. Lucy publicly chooses Ryn without surrendering her own political agency.', importance: 'Character' },
  { id: 'vagrant-city', era: 'Season 9', title: 'The unranked world is revealed', summary: 'Vagrant City and the Four Unrecorded Masters prove the Heavenly Register measures the known world rather than every powerful person alive.', importance: 'World' },
  { id: 'township-love', era: 'Season 10', title: 'Black Mountain becomes a community', summary: 'Refugees establish a free township at the mountain. Ryn refuses another accidental throne, and he and Lucy finally say they love each other.', importance: 'Character' },
  { id: 'six-houses', era: 'Season 11', title: 'The Six Ancient Houses return', summary: 'Iron Rain, Red Cedar, Glass Reed, Black River, White Ash, and Stone Veil emerge from outside the Register and fracture over Hollow Heaven’s direction.', importance: 'World' },
  { id: 'sovereigns-bleed', era: 'Season 12', title: 'The Five Sovereigns bleed', summary: 'All five are targeted simultaneously. Their feats preserve the prestige of the Heavenly Register while Lucy becomes a strategic target because of her own importance.', importance: 'World' },
  { id: 'still-sky', era: 'Season 13', title: 'Ryn reveals Still Sky', summary: 'During the Heavenless War, Lucy becomes coalition commander and Ryn learns to trust other people with fronts he cannot personally cover. He reveals his first named art, Still Sky.', importance: 'Arc' },
  { id: 'empty-throne', era: 'Season 14', title: 'The Empty Throne returns', summary: 'Black Register Entry II Mo Yejun defeats Seo Taewon and argues that the strongest person should rule. Ryn and Lucy reject both the throne and the ideology behind it.', importance: 'World' },
  { id: 'hollow-heaven-falls', era: 'Season 15', title: 'Home is not a throne', summary: 'Lucy dismantles Hollow Heaven’s command network, all five Sovereigns fight together, Ryn defeats Mo without claiming authority, and then proposes to Lucy on the cabin porch.', importance: 'Arc' },
];
