import type { LoreArticle } from './types';

export const loreArticles: LoreArticle[] = [
  { id: 'heavenly-register', title: 'The Heavenly Register', category: 'Power ranking', summary: 'The Celestial Record Pavilion ranks the hundred strongest publicly known martial artists. Even Rank #100 is a battlefield-level monster, and the second saga repeatedly demonstrates that registered fighters remain formidable even after unrecorded masters appear.', details: ['Ranks 100–51: Earthly Masters.', 'Ranks 50–21: Grandmasters.', 'Ranks 20–11: Ten Great Lords.', 'Ranks 10–6: Five Heavenly Pillars.', 'Ranks 5–1: Five Sovereigns.', 'Seo Taewon is Rank #1 / First Sovereign.', 'After the Hollow Heaven war, the Pavilion explicitly acknowledges that the Register is authoritative but not complete.'] },
  { id: 'black-register', title: 'The Black Register', category: 'Restricted record', summary: 'A secret Pavilion archive for beings who cannot safely or meaningfully be placed on the Heavenly Register.', details: ['Ryn is Black Register Entry III.', 'Mo Yejun was Black Register Entry II before being erased from official history.', 'Entry I remains unrevealed after Season 15.', 'Ryn’s file warns against comparative ranking.', 'The public Register once displayed Ryn above Rank #1 as UNRANKABLE.'] },
  { id: 'hollow-heaven', title: 'Hollow Heaven', category: 'Ancient martial order', summary: 'A political-martial compact predating the modern Pavilion, built around powerful houses that rejected centralized ranking.', details: ['Its Six Ancient Houses are Iron Rain, Red Cedar, Glass Reed, Black River, White Ash, and Stone Veil.', 'The Houses are not uniformly villainous and eventually split over Mo Yejun’s authoritarian direction.', 'Mo Yejun believes the strongest sovereign has both the right and obligation to rule.', 'Lucy’s coalition defeats Hollow Heaven by separating voluntary cooperation from submission.'] },
  { id: 'vagrant-city', title: 'Vagrant City', category: 'Unranked territory', summary: 'A hidden city where sect insignia and ranking disputes carry no legal authority and powerful martial artists may deliberately remain unrecorded.', details: ['Fen defeats Heavenly Register Rank #12 in a tea house.', 'The Four Unrecorded Masters are Fen, Grandmother Su, Orin, and Jae.', 'Ryn previously lived in Fen’s storage shed during an unexplained injured period of his past.', 'Vagrant City becomes a major intelligence and commercial ally for Lucy.'] },
  { id: 'five-sects', title: 'The Five Great Orthodox Sects', category: 'Martial order', summary: 'Five institutions whose authority defines accepted Orthodox martial conduct across much of the continent.', details: ['Heavenly Sword Palace — prestigious sword orthodoxy.', 'Nine Suns Monastery — body cultivation and overwhelming internal energy.', 'Jade Moon Sect — movement, medicine, and hidden weapons.', 'Azure Dragon Hall — militarized Orthodox authority.', 'Supreme Dao Sanctuary — ideological center of the Orthodox world.', 'They remain ideologically distinct from Ryn even after cooperating against Hollow Heaven.'] },
  { id: 'black-mountain', title: 'Black Mountain', category: 'Home and free township', summary: 'Ryn’s hermitage grows into the emotional center of the series without becoming the kingdom outsiders keep assuming he wants.', details: ['Lucy gradually begins calling the mountain home.', 'Refugees establish a self-governing township at its foot.', 'The charter explicitly denies Ryn personal rule.', 'The Black Mountain Coalition later coordinates from the township.', 'Ryn proposes to Lucy on the cabin porch after the Hollow Heaven war.'] },
  { id: 'ryn-morality', title: 'Why Ryn Is a Heretic', category: 'Character philosophy', summary: 'Ryn genuinely rejects institutional martial law and the idea that superior power automatically creates superior political authority.', details: ['He protects people regardless of Orthodox or unorthodox affiliation.', 'He will use overwhelming force but does not confuse victory with ownership.', 'He repeatedly refuses titles, kingdoms, followers, and finally Mo Yejun’s throne.', 'His central answer to tyranny is to stop the immediate harm and then let people choose what comes next.'] },
  { id: 'romance-philosophy', title: 'Ryn and Lucy: Choice Without Ownership', category: 'Relationship canon', summary: 'The romance develops through humor, ordinary intimacy, mutual trust, and the explicit rejection of protection becoming ownership.', details: ['Lucy retains political, investigative, and martial agency after the romance becomes official.', 'Ryn learns to trust Lucy’s plans and other allies rather than trying to solve every danger himself.', 'Lucy refuses a political marriage because she chooses her own future, not because Ryn threatens anyone.', 'Season 14 explicitly rejects the idea that love gives Lucy the right to make Ryn rule.', 'They become engaged in Season 15.'] },
];
