import type { Character } from './types';

export const characters: Character[] = [
  { id: 'ryn', name: 'Ryn', aliases: ['The Despicable Heretic', 'Uncrowned Mountain Sovereign'], role: 'Hermit · unrankable martial calamity', affiliation: 'Independent · Black Mountain', status: 'Active', importance: 'Core', description: 'An absurdly powerful hermit condemned as a villain by the Orthodox world. Ryn rejects institutional authority, refuses every throne offered to him, gradually learns to trust others, and becomes engaged to Lucy at the end of Season 15.', traits: ['apathetic', 'practical', 'quietly compassionate', 'freedom-minded', 'overwhelming'], accent: 'Winter' },
  { id: 'lucy', name: 'Lucy', aliases: ['Imperial Princess Lucy', 'Coalition Strategist'], role: 'Royal princess · political strategist · coalition commander', affiliation: 'Imperial House · Black Mountain Coalition', status: 'Active', importance: 'Core', description: 'A genuinely kind and funny royal princess with exceptional political instincts. Lucy grows into the coalition strategist who repeatedly solves problems Ryn cannot punch, preserves her independence throughout the romance, and becomes Ryn’s fiancée.', traits: ['kind', 'funny', 'fearless', 'observant', 'politically brilliant'], accent: 'Rose' },
  { id: 'seo-taewon', name: 'Seo Taewon', aliases: ['White Falcon Sovereign', 'Heavenly Register Rank #1', 'First Sovereign'], role: 'Highest publicly ranked martial artist', affiliation: 'Heavenly Register · Black Mountain Coalition', status: 'Active', importance: 'Major', description: 'The strongest publicly ranked martial artist and a genuine world-class monster. Taewon begins by measuring Ryn, becomes an ally and friend, defeats multiple ancient-house masters, and later loses a legendary duel to Mo Yejun without diminishing his status.', traits: ['disciplined', 'dryly funny', 'honorable', 'Sovereign', 'formidable'], accent: 'Tide' },
  { id: 'mo-yejun', name: 'Mo Yejun', aliases: ['The Empty Throne', 'Black Register Entry II'], role: 'Ancient unranked sovereign · Hollow Heaven leader', affiliation: 'Hollow Heaven', status: 'Active', importance: 'Major', description: 'An ancient sovereign erased from official history who believes overwhelming strength creates both the right and duty to rule. He defeats Seo Taewon, challenges Ryn philosophically and martially, and is ultimately defeated without Ryn claiming his throne.', traits: ['charismatic', 'authoritarian', 'ancient', 'philosophical', 'catastrophically strong'], accent: 'Ash' },
  { id: 'wei-cang', name: 'Wei Cang', aliases: ['The Smiling Archivist', 'Former Black Register Custodian'], role: 'Information manipulator · war instigator', affiliation: 'Former Celestial Record Pavilion · Hollow Heaven sympathizer', status: 'Active', importance: 'Major', description: 'A former Black Register custodian who weaponizes forged reports, false orders, and existing hatred to manufacture conflicts around Ryn. Lucy dismantles his network and denies him the martyrdom he wants.', traits: ['patient', 'manipulative', 'scholarly', 'theatrical'], accent: 'Ink' },
  { id: 'cassian', name: 'Cassian', aliases: ['Northern Crown Prince'], role: 'Northern prince · diplomatic ally', affiliation: 'Northern Crown', status: 'Active', importance: 'Major', description: 'The proposed groom in the Season 8 marriage treaty. Cassian is intelligent, honorable, uninterested in forcing the marriage, and becomes a useful ally after helping Lucy expose the economic causes of the northern conflict.', traits: ['diplomatic', 'observant', 'wry', 'honorable'], accent: 'Steel' },
  { id: 'lady-sen', name: 'Lady Sen', aliases: ['Master of Red Cedar'], role: 'Ancient house master', affiliation: 'House Red Cedar · Black Mountain Coalition', status: 'Active', importance: 'Major', description: 'Leader of Red Cedar, one of the Six Ancient Houses. She protects civilians before politics, refuses both Orthodox submission and Hollow Heaven extremism, and becomes a key coalition ally.', traits: ['pragmatic', 'compassionate', 'independent', 'powerful'], accent: 'Cedar' },
  { id: 'fen', name: 'Fen', aliases: ['Uncle Fen', 'Unrecorded Tea Master'], role: 'Tea-house owner · unrecorded master', affiliation: 'Vagrant City', status: 'Active', importance: 'Major', description: 'A cheerful Vagrant City tea seller strong enough to defeat Heavenly Register Rank #12. Fen knew Ryn from an earlier mysterious visit and represents the powerful masters who deliberately refuse ranking.', traits: ['cheerful', 'unrecorded', 'perceptive', 'very strong'], accent: 'Tea' },
  { id: 'rank-five', name: 'Fifth Sovereign', aliases: ['Heavenly Register Rank #5'], role: 'Five Sovereigns', affiliation: 'Heavenly Register · Black Mountain Coalition', status: 'Active', importance: 'Major', description: 'The first Sovereign to appear directly. During the Hollow Heaven war, Rank #5 survives an assassination formation built specifically to kill him while protecting civilians.', traits: ['terrifying', 'disciplined', 'resilient', 'Sovereign'], accent: 'Orchid' },
];
