export interface RankedMonster {
  rank: number;
  name: string;
  title: string;
  affinity: string;
  combatStyle: string;
  signatureArts: string[];
  distinction: string;
}

export const topTwenty: RankedMonster[] = [
  { rank: 1, name: 'Seo Taewon', title: 'White Falcon Sovereign', affinity: 'Wind / pressure', combatStyle: 'Absolute aerial control, pressure blades, and movement that erases distance.', signatureArts: ['Sky Has No Walls', 'Falcon Crossing Ten Miles', 'Pressure Burial'], distinction: 'Fastest publicly ranked martial artist. He owns vertical space so completely that armies treat open sky as hostile terrain.' },
  { rank: 2, name: 'Veyra Nox', title: 'Pale Serpent Sovereign', affinity: 'Poison / blood', combatStyle: 'Adaptive venom qi, blood-flow disruption, antidote inversion, and infection control.', signatureArts: ['Seven Organ Silence', 'Venom Scripture: Living Antidote', 'Black Pulse Contagion'], distinction: 'The most dangerous attrition fighter in the Register. Surviving her first poison only teaches the next one how to kill you.' },
  { rank: 3, name: 'Dae Kiryun', title: 'Stormbreak Sovereign', affinity: 'Lightning / magnetism', combatStyle: 'Explosive acceleration, magnetic field distortion, thunder-body reinforcement, and chained discharge.', signatureArts: ['Thunder Before Sound', 'Iron-Sky Discharge', 'Hundred Lightning Steps'], distinction: 'Highest instantaneous destructive output among the ranked Sovereigns and the hardest to pin down once he begins moving.' },
  { rank: 4, name: 'Maren Sol', title: 'Abyssal Tide Sovereign', affinity: 'Water / pressure / cold', combatStyle: 'Hydraulic force, pressure collapse, freezing currents, and redirection rather than direct collision.', signatureArts: ['Ocean Without Shore', 'Crushing Depth', 'Winter Current Reversal'], distinction: 'Best defensive Sovereign. She turns enemy force into terrain, pressure, and counterattack.' },
  { rank: 5, name: 'Kassian Ro', title: 'Ash-Furnace Sovereign', affinity: 'Fire / combustion', combatStyle: 'Furnace-body cultivation, compressed ignition, heat domains, and burning meridian pressure.', signatureArts: ['Furnace Body', 'Ashen Sun', 'Burning Meridian Catastrophe'], distinction: 'No other ranked fighter can sustain catastrophic heat for as long without exhausting their core.' },
  { rank: 6, name: 'Sael Vardon', title: 'Dune Regent', affinity: 'Sand / earth', combatStyle: 'Grinding sand qi, terrain collapse, abrasion, burial pressure, and long-range field control.', signatureArts: ['Dune Kingdom', 'Burial Under Nine Sands'], distinction: 'Turns flat land into layered kill-zones and strips armor, footing, and visibility from an opponent at once.' },
  { rank: 7, name: 'Orun Bale', title: 'Resonance Warden', affinity: 'Sound / vibration', combatStyle: 'Resonance attacks, internal shock, anti-weapon vibration, and disruption of technique rhythm.', signatureArts: ['Bell Without Metal', 'Heartbeat Fracture'], distinction: 'Breaks techniques by ruining their internal timing rather than overpowering their output.' },
  { rank: 8, name: 'Lysandra Keir', title: 'Dawn Edge', affinity: 'Wind / sword qi', combatStyle: 'Ultra-clean sword lines, short acceleration, pressure-thin cuts, and near-zero wasted motion.', signatureArts: ['Horizon in One Draw', 'Seven Returning Cuts'], distinction: 'The most technically precise swordswoman in the Register; she wins exchanges by needing fewer motions than everyone else.' },
  { rank: 9, name: 'Toren Vahl', title: 'Iron Orbit', affinity: 'Metal / magnetism', combatStyle: 'Weapon reinforcement, magnetic pull, orbiting metal fields, and armor-breaking impact control.', signatureArts: ['Iron Orbit', 'Weapon Rain Reversal'], distinction: 'Can turn every loose piece of metal in a battlefield into either a weapon or a liability.' },
  { rank: 10, name: 'Nyra Sen', title: 'White Thread', affinity: 'Venom / silk', combatStyle: 'Poisoned threads, hidden needles, layered trap geometry, and long-range meridian cuts.', signatureArts: ['White Thread Court', 'Venom Through Silk'], distinction: 'Physically fragile by Top 20 standards, but terrifying once her thread field is established.' },
  { rank: 11, name: 'Boran Dusk', title: 'Stone Maw Lord', affinity: 'Earth / body', combatStyle: 'Extreme body cultivation, shock absorption, crushing grapples, and short-range impact transfer.', signatureArts: ['Stone Maw Body', 'Mountain Breaker Clinch'], distinction: 'Hardest body in the Top 20 and one of the few Lords who willingly takes a Sovereign-class hit to create an opening.' },
  { rank: 12, name: 'Elian Mor', title: 'Mirage Glass Lord', affinity: 'Mist / illusion', combatStyle: 'Sensory distortion, false qi signatures, misdirection, and layered assassination angles.', signatureArts: ['Mirrored Breath Maze', 'Empty Street of Mist'], distinction: 'Can make one fighter appear to be an army and an army appear to contain nobody at all.' },
  { rank: 13, name: 'Veska Ren', title: 'Puppet Wire Lord', affinity: 'Thread / remote control', combatStyle: 'Qi wires, remote weapon control, joint-locking, and battlefield infrastructure manipulation.', signatureArts: ['Ten Funeral Wires', 'Puppet Line Severance'], distinction: 'Controls the space between people, doors, weapons, bridges, and formations more than the people themselves.' },
  { rank: 14, name: 'Kaio Draven', title: 'River Fang Lord', affinity: 'Water / beast-form qi', combatStyle: 'Predatory pursuit, water-coated claws, scent-like qi marking, and relentless chase pressure.', signatureArts: ['River Fang Pursuit', 'Flood-Beast Mantle'], distinction: 'Best tracker in the Top 20 and almost impossible to escape once he has marked a target.' },
  { rank: 15, name: 'Seline Arq', title: 'Ember Mercy Lord', affinity: 'Fire / healing', combatStyle: 'Cauterizing flame, restorative heat, precise meridian burns, and emergency battlefield medicine.', signatureArts: ['Ember Sutra: Gentle Burn', 'Cauterizing Mercy'], distinction: 'Can stabilize an ally and cripple an enemy with the same degree of flame control.' },
  { rank: 16, name: 'Corven Ash', title: 'Hollow Reed Lord', affinity: 'Shadow / concealment', combatStyle: 'Qi suppression, blind-angle movement, false absence, and silent killing.', signatureArts: ['No-Moon Passage', 'Breathless Shadow'], distinction: 'Lowest detectable qi signature among the Top 20; even experts often notice him only after he has already moved.' },
  { rank: 17, name: 'Tavia Moss', title: 'Root Calamity', affinity: 'Wood / plant qi', combatStyle: 'Regeneration, binding roots, toxin-bearing growth, and slow conversion of the battlefield into living terrain.', signatureArts: ['Root Dominion', 'Green Hunger'], distinction: 'The longer a fight continues, the more of the battlefield becomes part of her cultivation network.' },
  { rank: 18, name: 'Rook Arden', title: 'World-Weight Lord', affinity: 'Heavy qi / pressure', combatStyle: 'Crushing fields, momentum amplification, anti-mobility pressure, and impact multiplication.', signatureArts: ['World-Weight Field', 'Meteor Step'], distinction: 'Can make a single step feel like carrying a fortress and turn ordinary momentum into catastrophic force.' },
  { rank: 19, name: 'Joren Quill', title: 'Broken Tempo Lord', affinity: 'Pure sword qi', combatStyle: 'Deliberately ruined rhythm, false beats, broken cadence, and attacks released between expected timings.', signatureArts: ['Broken Measure', 'Seventh Beat Severing'], distinction: 'The hardest Top 20 fighter to read because his style is built around violating the timing assumptions experts rely on.' },
  { rank: 20, name: 'Luma Vey', title: 'Storm Lantern Lord', affinity: 'Water / lightning', combatStyle: 'Conductive rainfall, ranged current webs, area denial, and large-scale formation disruption.', signatureArts: ['Conductive Rainfield', 'Lantern Storm'], distinction: 'Lowest raw qi among the Top 20, but one of the most dangerous ranked fighters in wars and crowded battlefields.' },
];
