export interface RankedMonster {
  rank: number;
  name: string;
  title: string;
  affinity: string;
  combatStyle: string;
  signatureArts: string[];
  distinction: string;
}

/** Current Heavenly Register roster after the Season 33 succession. */
export const topTwenty: RankedMonster[] = [
  { rank: 1, name: 'Seo Taewon', title: 'White Falcon Sovereign', affinity: 'Wind / pressure', combatStyle: 'Absolute aerial control, pressure blades, and movement that erases distance.', signatureArts: ['Sky Has No Walls', 'Falcon Crossing Ten Miles', 'Pressure Burial'], distinction: 'Fastest publicly ranked martial artist. He remains Rank #1 through the intercontinental Guild War despite hostile network matchups.' },
  { rank: 2, name: 'Veyra Nox', title: 'Viridian Serpent Sovereign', affinity: 'Poison / blood', combatStyle: 'Adaptive venom qi, blood-flow disruption, antidote inversion, and infection control.', signatureArts: ['Seven Organ Silence', 'Venom Scripture: Living Antidote', 'Black Pulse Contagion'], distinction: 'The Register’s most dangerous attrition fighter and a physician whose medical judgment matters as much as her poison.' },
  { rank: 3, name: 'Dae Kiryun', title: 'Stormbreak Sovereign', affinity: 'Lightning / magnetism', combatStyle: 'Explosive acceleration, magnetic field distortion, thunder-body reinforcement, and chained discharge.', signatureArts: ['Thunder Before Sound', 'Iron-Sky Discharge', 'Hundred Lightning Steps'], distinction: 'Highest instantaneous destructive output among the public Sovereigns and the fastest multi-front responder after Taewon.' },
  { rank: 4, name: 'Maren Sol', title: 'Abyssal Tide Sovereign', affinity: 'Water / pressure / cold', combatStyle: 'Hydraulic force, pressure collapse, freezing currents, and redirection rather than direct collision.', signatureArts: ['Ocean Without Shore', 'Crushing Depth', 'Countercurrent Lock'], distinction: 'Best defensive Sovereign; repeatedly converts battlefield disasters into time and safe routes for civilians.' },
  { rank: 5, name: 'Sael Vardon', title: 'Dune Regent', affinity: 'Sand / earth', combatStyle: 'Grinding sand qi, terrain collapse, abrasion, burial pressure, and long-range field control.', signatureArts: ['Dune Kingdom', 'Burial Under Nine Sands'], distinction: 'Promoted after Kassian Ro’s death and deliberately keeps his own identity rather than imitating the former Rank #5.' },
  { rank: 6, name: 'Lysandra Keir', title: 'Dawn Edge', affinity: 'Wind / sword qi', combatStyle: 'Ultra-clean sword lines, short acceleration, pressure-thin cuts, and near-zero wasted motion.', signatureArts: ['Horizon in One Draw', 'Seven Returning Cuts'], distinction: 'Promoted after Orun Bale’s death; the Register’s most technically precise swordswoman.' },
  { rank: 7, name: 'Nyra Sen', title: 'Silent Loom', affinity: 'Venom / silk', combatStyle: 'Poisoned threads, hidden needles, layered trap geometry, and long-range meridian cuts.', signatureArts: ['Loom of Needles', 'Venom Through Silk'], distinction: 'Promoted after Toren Vahl’s death; physically fragile by upper-Register standards but terrifying once her field exists.' },
  { rank: 8, name: 'Boran Dusk', title: 'Stone Maw Lord', affinity: 'Earth / body', combatStyle: 'Extreme body cultivation, shock absorption, crushing grapples, and short-range impact transfer.', signatureArts: ['Stone Maw Body', 'Mountain Breaker Clinch'], distinction: 'Hardest body in the current Top 20 and unusually willing to take a superior hit to create an opening for others.' },
  { rank: 9, name: 'Elian Mor', title: 'Mirage Glass Lord', affinity: 'Mist / illusion', combatStyle: 'Sensory distortion, false qi signatures, misdirection, and layered assassination angles.', signatureArts: ['Mirrored Breath Maze', 'Empty Street of Mist'], distinction: 'Can make one fighter appear to be an army and an army appear to contain nobody at all.' },
  { rank: 10, name: 'Veska Ren', title: 'Puppet Wire Lord', affinity: 'Thread / remote control', combatStyle: 'Qi wires, remote weapon control, joint-locking, and battlefield infrastructure manipulation.', signatureArts: ['Ten Funeral Wires', 'Puppet Line Severance'], distinction: 'Controls relationships between people, doors, weapons, bridges, and formations rather than merely attacking bodies.' },
  { rank: 11, name: 'Kaio Draven', title: 'River Fang Lord', affinity: 'Water / beast-form qi', combatStyle: 'Predatory pursuit, water-coated claws, scent-like qi marking, and relentless chase pressure.', signatureArts: ['River Fang Pursuit', 'Flood-Beast Mantle'], distinction: 'Best tracker in the Top 20 and almost impossible to escape after he marks a target.' },
  { rank: 12, name: 'Seline Arq', title: 'Ember Mercy Lord', affinity: 'Fire / healing', combatStyle: 'Cauterizing flame, restorative heat, precise meridian burns, and emergency battlefield medicine.', signatureArts: ['Ember Sutra: Gentle Burn', 'Cauterizing Mercy'], distinction: 'Can stabilize an ally and cripple an enemy with the same degree of flame control.' },
  { rank: 13, name: 'Corven Ash', title: 'Hollow Reed Lord', affinity: 'Shadow / concealment', combatStyle: 'Qi suppression, blind-angle movement, false absence, and silent infiltration.', signatureArts: ['Blind-Corner Passage', 'Breathless Shadow'], distinction: 'Lowest detectable qi signature among the Top 20; his apparent Season 27 betrayal is later revealed as Lucy’s counterintelligence operation.' },
  { rank: 14, name: 'Tavia Moss', title: 'Thorn Regent', affinity: 'Wood / plant qi', combatStyle: 'Regeneration, binding roots, toxin-bearing growth, and slow conversion of the battlefield into living terrain.', signatureArts: ['Root Dominion', 'Green Hunger'], distinction: 'The longer a conflict lasts, the more terrain becomes part of her cultivation network.' },
  { rank: 15, name: 'Rook Arden', title: 'World-Weight Lord', affinity: 'Heavy qi / pressure', combatStyle: 'Crushing fields, momentum amplification, anti-mobility pressure, and impact multiplication.', signatureArts: ['World-Weight Field', 'Meteor Step'], distinction: 'Turns ordinary momentum into crushing battlefield force and adapts without embarrassment when countered.' },
  { rank: 16, name: 'Joren Quill', title: 'Broken Tempo Lord', affinity: 'Pure sword qi', combatStyle: 'Deliberately ruined rhythm, false beats, broken cadence, and attacks released between expected timings.', signatureArts: ['Broken Measure', 'Seventh Beat Severing'], distinction: 'One of the hardest ranked fighters to read because his style attacks experts’ timing assumptions.' },
  { rank: 17, name: 'Luma Vey', title: 'Storm Lantern Lord', affinity: 'Water / lightning', combatStyle: 'Conductive rainfall, ranged current webs, area denial, and large-scale formation disruption.', signatureArts: ['Conductive Rainfield', 'Lantern Storm'], distinction: 'A battlefield-scale specialist whose utility routinely exceeds fighters with greater raw qi.' },
  { rank: 18, name: 'Tessan Ri', title: 'Flow-Script Lord', affinity: 'Formation ink / conductive qi', combatStyle: 'Writes conductive qi through existing formations to reroute, invert, or falsify their internal flow after deployment.', signatureArts: ['Twelve-Line Reversal', 'Borrowed Formation Stroke'], distinction: 'Originally introduced at Rank #21; now a veteran Top-20 formation analyst whose work is central to both the Black Sun and Guild War.' },
  { rank: 19, name: 'Dalen Korr', title: 'Anchor Chain Lord', affinity: 'Force transfer / chain qi', combatStyle: 'Routes impact through linked anchors, chains, bridges, and structural contact points instead of resisting force directly.', signatureArts: ['Six-Anchor Transfer', 'Current Without Water'], distinction: 'Introduced at Rank #21 before Orun’s death. An Azure Dragon rescue captain who treats infrastructure and evacuation as martial responsibilities.' },
  { rank: 20, name: 'Iseul Venn', title: 'Echo Mercy Lord', affinity: 'Reflected qi / delayed impact', combatStyle: 'Creates delayed force-reflections of movements so one action can arrive multiple times at different moments for combat, rescue, or healing.', signatureArts: ['Three Returning Shadows', 'Mercy in the Second Step'], distinction: 'Introduced at Rank #22 as a Jade Moon night-clinic physician. After the sect dissolves and later Top-20 losses occur, she reaches #20 without abandoning medicine.' },
];

export const formerTopTwenty = [
  { rank: 5, name: 'Kassian Ro', title: 'Ash-Furnace Sovereign', status: 'Deceased', finalSeason: 19, distinction: 'Died after saving populated villages from the Eclipse heat catastrophe. His death caused the Season 20 succession.' },
  { rank: 6, name: 'Orun Bale', title: 'Resonance Warden', status: 'Deceased', finalSeason: 29, distinction: 'Died redirecting the Choir Crown’s mountain-breaking resonance into himself so Azure Dragon evacuation routes remained open.' },
  { rank: 7, name: 'Toren Vahl', title: 'Iron Orbit', status: 'Deceased', finalSeason: 33, distinction: 'Died containing a cascading Concord relay failure in the foundry belt after helping thousands of civilians and soldiers escape.' },
] as const;
