export interface RankedMonster {
  rank: number;
  name: string;
  title: string;
  affinity: string;
  combatStyle: string;
  signatureArts: string[];
  distinction: string;
}

/** Current Heavenly Register roster after the Season 53 post-Taewon reassessment. */
export const topTwenty: RankedMonster[] = [
  { rank: 1, name: 'Veyra Nox', title: 'Viridian Serpent Sovereign', affinity: 'Poison / blood', combatStyle: 'Adaptive venom qi, blood-flow disruption, antidote inversion, anatomy, and battlefield medicine.', signatureArts: ['Seven Organ Silence', 'Venom Scripture: Living Antidote', 'Black Pulse Contagion'], distinction: 'Accepts Rank #1 after Seo Taewon dies in Season 52. She treats the number as work rather than inheritance and remains the Register’s greatest physician-combatant.' },
  { rank: 2, name: 'Dae Kiryun', title: 'Stormbreak Sovereign', affinity: 'Lightning / magnetism', combatStyle: 'Explosive acceleration, magnetic field distortion, thunder-body reinforcement, and chained discharge.', signatureArts: ['Thunder Before Sound', 'Iron-Sky Discharge', 'Hundred Lightning Steps'], distinction: 'Moves to #2 after Taewon’s death. Kaiven defeats him by exploiting his instinct to arrive where people need him, but Ryn reconstructs the resulting spinal damage.' },
  { rank: 3, name: 'Sael Vardon', title: 'Dune Regent', affinity: 'Sand / earth', combatStyle: 'Grinding sand qi, terrain collapse, abrasion, burial pressure, and long-range field control.', signatureArts: ['Dune Kingdom', 'Burial Under Nine Sands'], distinction: 'Now Rank #3. Sael survives the Rank Hunter’s upper-Register climb and continues treating rank as responsibility rather than identity.' },
  { rank: 4, name: 'Lysandra Keir', title: 'Dawn Edge', affinity: 'Wind / sword qi', combatStyle: 'Ultra-clean sword lines, short acceleration, pressure-thin cuts, and near-zero wasted motion.', signatureArts: ['Horizon in One Draw', 'Seven Returning Cuts'], distinction: 'Now Rank #4. She pushes Kaiven hard enough to permanently damage several Hundred Graves partitions and later gives Lucy the final Top-Five assessment fight.' },
  { rank: 5, name: 'Lucy', title: 'First Steward', affinity: 'Pure qi / pressure / adaptive fundamentals', combatStyle: 'Highly efficient circulation, predictive positioning, pressure redirection, route control, and cross-discipline fundamentals learned from Open Gate’s masters.', signatureArts: ['Steward’s Measure', 'Rose Compass Step', 'Open Gate Counterflow'], distinction: 'Princess Lucy becomes formal Rank #5 in Season 53 after years of accelerated but personally retained growth inside Spring of the Open Gate. She remains First Steward rather than adopting a Sovereign title.' },
  { rank: 6, name: 'Nyra Sen', title: 'Silent Loom', affinity: 'Venom / silk', combatStyle: 'Poisoned threads, hidden needles, layered trap geometry, and long-range meridian cuts.', signatureArts: ['Loom of Needles', 'Venom Through Silk'], distinction: 'Now Rank #6. Survives Kaiven’s hunt and emerges stronger after Myriad Spring Reforging repairs old shoulder and poison-training damage.' },
  { rank: 7, name: 'Boran Dusk', title: 'Stone Maw Lord', affinity: 'Earth / body', combatStyle: 'Extreme body cultivation, shock absorption, crushing grapples, and short-range impact transfer.', signatureArts: ['Stone Maw Body', 'Mountain Breaker Clinch'], distinction: 'Now Rank #7. Kaiven defeats him by exploiting his instinct to protect juniors, but Ryn’s healing removes decades of accumulated body-cultivation damage and strengthens his foundation.' },
  { rank: 8, name: 'Meira Sun', title: 'The Moonless Arrow', affinity: 'Long-range qi / trajectory control', combatStyle: 'Extreme-range qi archery, curved trajectories, formation-node sniping, and battlefield observation from impossible distances.', signatureArts: ['Moonless Flight', 'Arrow Beyond the Ridge'], distinction: 'Former Rank #7 who voluntarily vanished after refusing an Orthodox execution order. She joins Open Gate as an instructor and accepts reassessment in Season 53, returning to the Register at #8.' },
  { rank: 9, name: 'Elian Mor', title: 'Mirage Glass Lord', affinity: 'Mist / illusion', combatStyle: 'Sensory distortion, false qi signatures, misdirection, and layered assassination angles.', signatureArts: ['Mirrored Breath Maze', 'Empty Street of Mist'], distinction: 'Can make one fighter appear to be an army and an army appear to contain nobody at all.' },
  { rank: 10, name: 'Veska Ren', title: 'Puppet Wire Lord', affinity: 'Thread / remote control', combatStyle: 'Qi wires, remote weapon control, joint-locking, and battlefield infrastructure manipulation.', signatureArts: ['Ten Funeral Wires', 'Puppet Line Severance'], distinction: 'Kaiven defeats her without touching her body, but she breaks her own strongest field before it becomes a predictable cage.' },
  { rank: 11, name: 'Kaio Draven', title: 'River Fang Lord', affinity: 'Water / beast-form qi', combatStyle: 'Predatory pursuit, water-coated claws, qi marking, and relentless chase pressure.', signatureArts: ['River Fang Pursuit', 'Flood-Beast Mantle'], distinction: 'The Rank Hunter defeats him after feeding false circulation cues through his pursuit mark, but Kaio survives and remains one of the Register’s premier trackers.' },
  { rank: 12, name: 'Seline Arq', title: 'Ember Mercy Lord', affinity: 'Fire / healing', combatStyle: 'Cauterizing flame, restorative heat, precise meridian burns, and emergency battlefield medicine.', signatureArts: ['Ember Sutra: Gentle Burn', 'Cauterizing Mercy'], distinction: 'Can stabilize an ally and cripple an enemy with the same degree of flame control.' },
  { rank: 13, name: 'Corven Ash', title: 'Hollow Reed Lord', affinity: 'Shadow / concealment', combatStyle: 'Qi suppression, blind-angle movement, false absence, and silent infiltration.', signatureArts: ['Blind-Corner Passage', 'Breathless Shadow'], distinction: 'Lowest detectable qi signature among the Top 20 and a long-term intelligence ally of Lucy.' },
  { rank: 14, name: 'Tavia Moss', title: 'Thorn Regent', affinity: 'Wood / plant qi', combatStyle: 'Regeneration, binding roots, toxin-bearing growth, and slow conversion of the battlefield into living terrain.', signatureArts: ['Root Dominion', 'Green Hunger'], distinction: 'The longer a conflict lasts, the more terrain becomes part of her cultivation network.' },
  { rank: 15, name: 'Joren Quill', title: 'Broken Tempo Lord', affinity: 'Pure sword qi', combatStyle: 'Deliberately ruined rhythm, false beats, broken cadence, and attacks released between expected timings.', signatureArts: ['Broken Measure', 'Seventh Beat Severing'], distinction: 'Kaiven defeats him only after using a circulation pattern from a dead swordsman Joren once knew, proving memory can be a combat weakness without diminishing Joren’s technical brilliance.' },
  { rank: 16, name: 'Luma Vey', title: 'Storm Lantern Lord', affinity: 'Water / lightning', combatStyle: 'Conductive rainfall, ranged current webs, area denial, and large-scale formation disruption.', signatureArts: ['Conductive Rainfield', 'Lantern Storm'], distinction: 'A battlefield-scale specialist whose utility routinely exceeds fighters with greater raw qi.' },
  { rank: 17, name: 'Tessan Ri', title: 'Flow-Script Lord', affinity: 'Formation ink / conductive qi', combatStyle: 'Writes conductive qi through existing formations to reroute, invert, or falsify their internal flow after deployment.', signatureArts: ['Twelve-Line Reversal', 'Borrowed Formation Stroke'], distinction: 'A central architect of the Thousand Lantern Network and World Meridian monitoring system.' },
  { rank: 18, name: 'Iseul Venn', title: 'Echo Mercy Lord', affinity: 'Reflected qi / delayed impact', combatStyle: 'Creates delayed force-reflections so one action can arrive multiple times for combat, rescue, or healing.', signatureArts: ['Three Returning Shadows', 'Mercy in the Second Step'], distinction: 'Open Gate Mercy Hall Master and Warden of Mercy. She remains a physician first even as Open Gate becomes one of the largest sources of ranked fighters.' },
  { rank: 19, name: 'Sorin Vale', title: 'Crossroad Lord', affinity: 'Pure qi / tactical field control', combatStyle: 'Low-signature movement, battlefield markers, predictive positioning, and command structures that make every route an increasingly bad choice.', signatureArts: ['Nine-Line Decision', 'Crossroad Without Exit'], distinction: 'Open Gate’s Warden of the Empty Gate. Kaiven’s failed attempt to hunt him becomes one of the first proofs that Open Gate’s cross-training can corrupt the Rank Hunter’s curriculum.' },
  { rank: 20, name: 'Kesh Ardan', title: 'Glassfire Lord', affinity: 'Glass / heat / structural control', combatStyle: 'Glass threads, heat-shaping, transparent traps, terrain conversion, and aggressive close-range improvisation.', signatureArts: ['Glass Solves Problems', 'Transparent Funeral Line'], distinction: 'Open Gate’s Warden of the Hand. He enters the Top 20 after Dalen retires and remains there through the Rank Hunter crisis.' },
];

export const formerTopTwenty = [
  { rank: 5, name: 'Kassian Ro', title: 'Ash-Furnace Sovereign', status: 'Deceased', finalSeason: 19, distinction: 'Died saving populated villages from the Eclipse heat catastrophe.' },
  { rank: 6, name: 'Orun Bale', title: 'Resonance Warden', status: 'Deceased', finalSeason: 29, distinction: 'Died keeping Azure Dragon evacuation routes open.' },
  { rank: 7, name: 'Toren Vahl', title: 'Iron Orbit', status: 'Deceased', finalSeason: 33, distinction: 'Died containing a cascading Concord relay failure.' },
  { rank: 4, name: 'Maren Sol', title: 'Abyssal Tide Sovereign', status: 'Deceased', finalSeason: 42, distinction: 'Held a World Meridian pressure rupture for hours so roughly 2.7 million people could evacuate.' },
  { rank: 18, name: 'Dalen Korr', title: 'Anchor Chain Lord', status: 'Retired', finalSeason: 48, distinction: 'Survives Kaiven’s inverted force-transfer attack but loses safe Top-20 use of Six-Anchor Transfer. He becomes a Wayfinder Hall instructor.' },
  { rank: 14, name: 'Rook Arden', title: 'World-Weight Lord', status: 'Retired', finalSeason: 49, distinction: 'Survives Kaiven’s attack but can no longer safely sustain World-Weight Field at ranked scale. He remains an Open Gate defensive instructor.' },
  { rank: 1, name: 'Seo Taewon', title: 'White Falcon Sovereign', status: 'Deceased', finalSeason: 52, distinction: 'Dies fighting Kaiven Rhoss on Skyglass Plateau after forcing Hundred Graves Scripture fully open and transmitting the decisive combat data through the Thousand Lantern Network.' },
] as const;
