import type { Villain } from './types';

export const villains: Villain[] = [
  { id: 'palace-conspirators', name: 'The Palace Conspirators', group: 'Imperial Coup Arc', threat: 3, status: 'Defeated', objective: 'Remove Lucy and seize control of the imperial succession.', description: 'A network of nobles and martial operatives behind repeated attempts on Lucy’s life. Their greatest mistake is forcing Ryn to care about palace politics.', tags: ['Lucy', 'assassins', 'imperial court'] },
  { id: 'wei-cang', name: 'Wei Cang — The Smiling Archivist', group: 'Manufactured War Arc', threat: 4, status: 'Defeated', objective: 'Use forged records, false orders, and manipulated violence to provoke Ryn into exposing his power and destabilize the existing martial order.', description: 'The former Black Register custodian behind the Hidden Instigator plot. Lucy defeats him by dismantling his information network and forcing him into an ordinary public trial instead of the martyrdom he wants.', tags: ['Wei Cang', 'Black Register', 'conspiracy', 'Lucy'] },
  { id: 'formation-mastermind', name: 'Heaven-Locking Mastermind', group: 'Supreme Dao Trial', threat: 5, status: 'Defeated', objective: 'Trap the Orthodox leadership and exploit the trial of the Despicable Heretic.', description: 'The faction behind the ancient Heaven-Locking Formation capable of suppressing thousands of martial artists and even hindering a Sovereign.', tags: ['Heaven-Locking Formation', 'trial', 'Sovereign'] },
  { id: 'hollow-heaven', name: 'Hollow Heaven', group: 'Six Ancient Houses Saga', threat: 5, status: 'Defeated', objective: 'Restore an ancient martial order outside the Heavenly Register and ultimately subordinate the public world to the Empty Throne.', description: 'An ancient compact older than the modern Pavilion. Its Six Houses are not uniformly villainous; several defect or cooperate with Lucy once Mo Yejun turns the compact into authoritarian rule.', tags: ['Six Houses', 'war', 'unranked masters', 'Hollow Heaven'] },
  { id: 'mo-yejun', name: 'Mo Yejun — The Empty Throne', group: 'Hollow Heaven War', threat: 5, status: 'Defeated', objective: 'Create a stable world ruled openly by the strongest martial sovereign, eventually offering that throne to Ryn.', description: 'Black Register Entry II and the greatest direct martial threat of the second saga. Mo defeats Rank #1 Seo Taewon and argues that overwhelming strength creates political ownership. Ryn defeats him while explicitly refusing the throne.', tags: ['Mo Yejun', 'Black Register', 'Ryn', 'philosophy', 'final boss'] },
];
