import type { Villain } from './types';

export const villains: Villain[] = [
  { id: 'palace-conspirators', name: 'The Palace Conspirators', group: 'Imperial Coup Arc', threat: 3, status: 'Defeated', objective: 'Remove Lucy and seize control of the imperial succession.', description: 'A network of nobles and martial operatives behind repeated attempts on Lucy’s life. Their greatest mistake is forcing Ryn to care about palace politics.', tags: ['Lucy', 'assassins', 'imperial court'] },
  { id: 'wei-cang', name: 'Wei Cang — The Smiling Archivist', group: 'Manufactured War Arc', threat: 4, status: 'Defeated', objective: 'Use forged records, false orders, and manipulated violence to provoke Ryn into exposing his power and destabilize the existing martial order.', description: 'The former Black Register custodian behind the Hidden Instigator plot. Lucy defeats him by dismantling his information network and forcing him into an ordinary public trial instead of the martyrdom he wants.', tags: ['Wei Cang', 'Black Register', 'conspiracy', 'Lucy'] },
  { id: 'formation-mastermind', name: 'Heaven-Locking Mastermind', group: 'Supreme Dao Trial', threat: 5, status: 'Defeated', objective: 'Trap the Orthodox leadership and exploit the trial of the Despicable Heretic.', description: 'The faction behind the ancient Heaven-Locking Formation capable of suppressing thousands of martial artists and even hindering a Sovereign.', tags: ['Heaven-Locking Formation', 'trial', 'Sovereign'] },
  { id: 'hollow-heaven', name: 'Hollow Heaven', group: 'Six Ancient Houses Saga', threat: 5, status: 'Dissolved', objective: 'Restore an ancient martial order outside the Heavenly Register and ultimately subordinate the public world to the Empty Throne.', description: 'An ancient compact older than the modern Pavilion. Its Six Houses are not uniformly villainous; several defect or cooperate with Lucy once Mo Yejun turns the compact into authoritarian rule. Its command network is dismantled in Season 15.', tags: ['Six Houses', 'war', 'unranked masters', 'Hollow Heaven'] },
  { id: 'mo-yejun', name: 'Mo Yejun — The Empty Throne', group: 'Hollow Heaven War', threat: 5, status: 'Defeated', objective: 'Create a stable world ruled openly by the strongest martial sovereign, eventually offering that throne to Ryn.', description: 'Black Register Entry II and the greatest direct martial threat of the Hollow Heaven saga. Mo defeats Rank #1 Seo Taewon and argues that overwhelming strength creates political ownership. Ryn defeats him while explicitly refusing the throne.', tags: ['Mo Yejun', 'Black Register', 'Ryn', 'philosophy'] },
  { id: 'eclipse-court', name: 'The Eclipse Court', group: 'Eclipse Court Saga', threat: 5, status: 'Dissolved', objective: 'Profile, counter, and neutralize the modern Heavenly Register through specialized anti-affinity cultivation and predictive combat data.', description: 'A western counter-cultivation order whose Seats study live combat decisions rather than merely raw techniques. Its Black Sun Array reduces famous fighters to predictive categories until Lucy deliberately breaks those categories and Tessan Ri corrupts the data itself.', tags: ['Eclipse Court', 'Top 20', 'counter-cultivation', 'Black Sun Array'] },
  { id: 'crownless-kings', name: 'The Five Crownless Kings', group: 'Eclipse Court Saga', threat: 5, status: 'Defeated', objective: 'Break the Five Sovereigns and provide the Eclipse Court with complete apex-combat data.', description: 'Ash King, Drought King, Iron Sky King, Bone Saint, and First Seat are hostile matchups built for the Sovereigns rather than generic stronger replacements. Their battles seriously injure the Top Five and establish that counter-design can threaten even apex ranked fighters.', tags: ['Sovereigns', 'Top 5', 'Eclipse Court', 'bosses'] },
  { id: 'aurel-veyr', name: 'Aurel Veyr — The Sunless Emperor', group: 'Eclipse Court Saga', threat: 5, status: 'Deceased', objective: 'Prove that modern specialization is a weakness and build a martial order capable of surviving the return of the First Silence.', description: 'Leader of the Eclipse Court. Eclipse Meridian suppresses external martial expression strongly enough to matter even against a fraction of Ryn’s released qi. Aurel weaponizes the wounded roster after Kassian Ro’s death, loses the Black Sun war, and dies after his own collapsing technique destroys him. His final warning reveals the First Silence.', tags: ['Aurel Veyr', 'Eclipse Meridian', 'Ryn', 'suppression', 'deceased'] },
  { id: 'five-severed-stars', name: 'The Five Severed Stars', group: 'Silent Age Saga', threat: 5, status: 'Reformed', objective: 'Originally suppress broad families of cultivation so the Quiet Gate can weaken the world without immediate resistance.', description: 'Neris Kaun, Rath Odan, Caldrin Mott, Hessa Dorn, and Varo Kest each carry a personal grievance rooted in martial abuse. By Season 24 they make independent choices, help reconstruction, and assist in dismantling the Quiet Gate.', tags: ['Neris Kaun', 'Rath Odan', 'Caldrin Mott', 'Hessa Dorn', 'Varo Kest', 'Severed Stars'] },
  { id: 'yeon-mugyeol', name: 'Yeon Mu-gyeol — The First Silence', group: 'Silent Age Saga', threat: 5, status: 'Reformed', objective: 'Originally end permanent martial hierarchy by severing humanity’s relationship with ambient qi and making cultivation impossible.', description: 'Black Register Entry I begins as a reformer rather than a conqueror. His Severing Palm can disconnect relationships between cultivators and qi and can briefly disrupt even Ryn. Lucy does not defeat his grievances; she offers reform, backup infrastructure, oversight, and preserved choice. Mu-gyeol eventually helps dismantle the Quiet Gate.', tags: ['Yeon Mu-gyeol', 'Black Register Entry I', 'Quiet Gate', 'First Silence', 'philosophy'] },

  { id: 'iron-concord', name: 'Iron Concord Guild', group: 'War Beyond the Register', threat: 5, status: 'Defeated', objective: 'Impose Arclune-style stabilization on the eastern continent through linked military occupation and guild administration.', description: 'Arclune’s No.1 guild invades with Banner Legions, fleets, War Crowns, engineers, healers, intelligence bureaus, and a linked cultivation doctrine. Its danger comes from coordinated institutions rather than one stronger boss. Lucy dismantles the strategic system around the army, defections fracture the invasion, and Cyran Vol finally concedes after the linked-war structure is safely separated from ordinary soldiers.', tags: ['Iron Concord', 'Arclune', 'Guild War', 'Banner Legions', 'Cyran Vol'] },
  { id: 'cyran-vol', name: 'Cyran Vol — The Concord Marshal', group: 'War Beyond the Register', threat: 5, status: 'Defeated', objective: 'Create durable order through disciplined guild rule and prevent fragmented martial societies from collapsing into repeated catastrophe.', description: 'Guildmaster of the Iron Concord. Cyran is individually Sovereign-tier, but his defining threat is Concordance: a military network that lets armies share force, senses, defense, and decision-making. Ryn can overpower him personally, but doing so carelessly would endanger linked soldiers. Lucy therefore wins the strategic war before Ryn wins the final clean duel.', tags: ['Cyran Vol', 'Concordance', 'Arclune', 'Ryn', 'Lucy'] },
  { id: 'pavilion-contingency-betrayal', name: 'The Pavilion Contingency Betrayal', group: 'War Beyond the Register', threat: 4, status: 'Defeated', objective: 'Secure a foreign guarantor against a future Black Register catastrophe by secretly trading capability data and defensive knowledge.', description: 'The Pavilion Master’s old contingency pact becomes the real betrayal behind the Iron Concord invasion. His motive is fear and institutional survival rather than greed, but he sells weaknesses belonging to people who trusted the Pavilion and destroys the neutrality that gave the Register legitimacy. The Pavilion survives only through public exposure, distributed oversight, and reduced secrecy.', tags: ['Celestial Record Pavilion', 'betrayal', 'Pavilion Master', 'Corven Ash', 'counterintelligence'] },
  { id: 'restoration-mandate', name: 'The Restoration Mandate', group: 'Empty Thrones Saga', threat: 4, status: 'Dissolved', objective: 'Rebuild the old Orthodox order by using fear of foreign power, sect collapse, and Open Gate’s rise to justify renewed centralized authority.', description: 'A movement of displaced Orthodox survivors and conservative elders rather than a cartoon cult. Its members believe Lucy and Ryn helped destroy the institutions that once gave the continent stability. An assassination attempt on Veyra and later political conflict expose the movement, while Open Gate’s refusal to answer dissent with arbitrary founder rule deprives it of the crisis it needs. The Mandate fractures rather than disappearing through one duel.', tags: ['Restoration Mandate', 'Orthodox', 'Veyra', 'Open Gate', 'politics'] },
  { id: 'kaor-ren', name: 'Kaor Ren — The Empty Throne', group: 'World Meridian Saga', threat: 5, status: 'Defeated', objective: 'Force worldwide ambient-qi equalization so geography can no longer determine which regions inherit superior cultivation opportunity.', description: 'The most dangerous political mind among Varkesh’s Seven Thrones. Kaor spends decades manipulating Throne succession around World Meridian junctions. His grievance is real: qi-rich geography creates inherited opportunity inequality. His forced solution would catastrophically collapse meridian-dependent medicine, agriculture, infrastructure, ecosystems, and cultivators across multiple continents. Ryn stops the equalization without using a second Supreme or the Ultimate, while Lucy answers the grievance with the Meridian Compact rather than restoration of the old unequal status quo.', tags: ['Kaor Ren', 'Seven Thrones', 'World Meridian', 'Varkesh', 'Ryn', 'Lucy'] },
];
