import type { Villain } from './types';

export const villains: Villain[] = [
  { id: 'palace-conspirators', name: 'The Palace Conspirators', group: 'Imperial Coup Arc', threat: 3, status: 'Defeated', objective: 'Remove Lucy and seize imperial succession.', description: 'The early palace network that forces Lucy and Ryn into imperial politics.', tags: ['Lucy', 'assassins', 'imperial court'] },
  { id: 'wei-cang', name: 'Wei Cang — The Smiling Archivist', group: 'Manufactured War Arc', threat: 4, status: 'Defeated', objective: 'Weaponize forged records and existing hatred around Ryn.', description: 'A former Black Register custodian defeated primarily by Lucy’s information strategy rather than Ryn’s strength.', tags: ['Wei Cang', 'Black Register', 'conspiracy'] },
  { id: 'hollow-heaven', name: 'Hollow Heaven', group: 'Six Ancient Houses Saga', threat: 5, status: 'Dissolved', objective: 'Restore an ancient martial order and ultimately subordinate the public world to the Empty Throne.', description: 'An older compact whose authoritarian turn under Mo Yejun is dismantled in S15.', tags: ['Hollow Heaven', 'Six Houses', 'war'] },
  { id: 'mo-yejun', name: 'Mo Yejun — The Empty Throne', group: 'Hollow Heaven War', threat: 5, status: 'Defeated', objective: 'Create a world ruled openly by the strongest sovereign.', description: 'Black Register Entry II defeats Seo Taewon and argues strength creates political ownership. Ryn defeats him while refusing the throne.', tags: ['Mo Yejun', 'Black Register', 'Ryn', 'philosophy'] },
  { id: 'eclipse-court', name: 'The Eclipse Court', group: 'Eclipse Court Saga', threat: 5, status: 'Dissolved', objective: 'Profile and counter the modern Heavenly Register through anti-affinity cultivation and prediction.', description: 'Its Black Sun system reduces famous fighters to categories until Lucy and Tessan corrupt the assumptions.', tags: ['Eclipse Court', 'Top 20', 'Black Sun'] },
  { id: 'aurel-veyr', name: 'Aurel Veyr — The Sunless Emperor', group: 'Eclipse Court Saga', threat: 5, status: 'Deceased', objective: 'Create a counter-cultivation order capable of surviving the First Silence.', description: 'Leader of Eclipse Court. Dies after the Black Sun collapse and warns of Yeon Mu-gyeol.', tags: ['Aurel Veyr', 'Ryn', 'suppression'] },
  { id: 'yeon-mugyeol', name: 'Yeon Mu-gyeol — The First Silence', group: 'Silent Age Saga', threat: 5, status: 'Reformed', objective: 'Originally end permanent martial hierarchy by severing humanity from ambient qi.', description: 'Black Register Entry I begins as a reformer whose exhaustion becomes abolitionism. He eventually helps dismantle the Quiet Gate.', tags: ['First Silence', 'Quiet Gate', 'Black Register'] },
  { id: 'iron-concord', name: 'Iron Concord Guild', group: 'War Beyond the Register', threat: 5, status: 'Defeated', objective: 'Use disciplined Guild-State military integration to impose “stability” on the eastern continent.', description: 'Arclune’s No.1 Guild invades with Banner Legions and Concordance. Lucy dismantles the military network before Ryn defeats Cyran as an individual.', tags: ['Arclune', 'Guild War', 'Cyran Vol'] },
  { id: 'cyran-vol', name: 'Cyran Vol — The Concord Marshal', group: 'War Beyond the Register', threat: 5, status: 'Defeated', objective: 'Prove centralized guild discipline is more humane than fragmented sect rule.', description: 'Individually Sovereign-tier and strategically more dangerous while linked to armies. Concedes after Lucy separates the institution from the man.', tags: ['Cyran Vol', 'Iron Concord', 'Concordance'] },
  { id: 'restoration-mandate', name: 'Restoration Mandate', group: 'World Meridian Saga', threat: 4, status: 'Dissolved', objective: 'Restore the old Orthodox order after foreign war, sect collapse, and Open Gate expansion.', description: 'A morally mixed conservative movement whose radical cells attack the new order. It fractures after public exposure and internal disagreement.', tags: ['Orthodox', 'betrayal', 'Open Gate'] },
  { id: 'kaor-ren', name: 'Kaor Ren — The Empty Throne of Varkesh', group: 'World Meridian Saga', threat: 5, status: 'Defeated', objective: 'Force global ambient-qi equalization through the World Meridian.', description: 'His grievance against geography-based cultivation inequality is legitimate, but forced equalization would kill millions. He survives and surrenders Meridian research after the plan fails.', tags: ['Varkesh', 'World Meridian', 'Seven Thrones'] },
  { id: 'kaiven-rhoss', name: 'Kaiven Rhoss — The Rank Hunter', group: 'Rank Hunter Saga', threat: 5, status: 'Defeated', objective: 'Prove the Heavenly Register is institutional fiction by hunting its ranked masters and building a complete martial curriculum from their crisis responses.', description: 'Former secret Pavilion Examiner Zero. Hundred Graves Scripture stores structural and decision patterns from defeated fighters until Kaiven becomes a walking archive of incompatible martial answers. He defeats multiple Top-Ten fighters and kills Seo Taewon #1. After realizing Open Gate has become a second martial curriculum, he tries to externalize Hundred Graves into the World Meridian. Ryn’s Supreme One Blossom Buries Heaven destroys the Scripture itself while leaving Kaiven alive for public trial.', tags: ['Rank Hunter', 'Kaiven Rhoss', 'Hundred Graves Scripture', 'Taewon', 'Examiner Zero'] },
  { id: 'broken-ledger', name: 'The Broken Ledger', group: 'Rank Hunter Saga', threat: 4, status: 'Dissolved', objective: 'Attack rank institutions, famous masters, and Open Gate in the name of anti-ranking grievance.', description: 'Leaderless imitators inspired by Kaiven despite his refusal to lead them. Their decentralized real emergencies expose the limits of even the Thousand Lantern Network and indirectly create the twenty-three-second extraction gap during Taewon’s final duel. Open Gate defeats the movement as a network rather than through one leader.', tags: ['Broken Ledger', 'Rank Hunter', 'Thousand Lanterns'] },
];
