import type { Faction } from './types';

export const factions: Faction[] = [
  { id: 'five-great-orthodox-sects', name: 'Five Great Orthodox Sects', category: 'Former Orthodox hegemony', alignment: 'Mixed', summary: 'The original five institutions were Heavenly Sword Palace, Nine Suns Monastery, Jade Moon Sect, Azure Dragon Hall, and Supreme Dao Sanctuary. By Season 30 the phrase is historically important but no longer literally true: Azure Dragon Hall has fallen as a physical seat and Jade Moon Sect has dissolved after internal collaboration and civil fracture. Heavenly Sword, Nine Suns, and Supreme Dao remain intact but increasingly reform under pressure from the new world.', members: ['Heavenly Sword Palace', 'Nine Suns Monastery', 'Supreme Dao Sanctuary', 'Azure Dragon Fellowship (successor network)', 'Moonwell Medical Network (Jade Moon successor network)'] },
  { id: 'open-gate', name: 'Open Gate', category: 'Independent martial school / sect network', alignment: 'Allied', summary: 'Founded reluctantly by Ryn and Lucy after the Guild War. Open Gate separates martial authority from political authority: Ryn is Mountain Teacher while Lucy is First Steward. It uses four permanent Halls, functional Gate Warden seats, non-hereditary Gatekeepers, and disciple levels that do not automatically confer command. Its defining doctrine is that strength creates responsibility rather than ownership.', members: ['Ryn — Mountain Teacher', 'Lucy — First Steward', 'Mountain Hall', 'Wayfinder Hall', 'Mercy Hall', 'Steward Hall', 'Nine Gate Warden Seats', 'Gatekeepers', 'First Gate'] },
  { id: 'celestial-record-pavilion', name: 'Celestial Record Pavilion', category: 'Ranking and capability authority', alignment: 'Allied', summary: 'The organization responsible for the Heavenly Register and Black Register survives the Pavilion Master betrayal only by exposing records, decentralizing authority, and accepting oversight. It continues to maintain historical succession and capability profiles rather than pretending a rank number erases matchup context or death.', members: ['Register observers', 'Black Register custodians', 'capability analysts', 'Tessan Ri and technical collaborators'] },
  { id: 'imperial-house', name: 'Imperial House', category: 'Royal dynasty', alignment: 'Allied', summary: 'Lucy’s royal family remains a major political anchor without claiming Black Mountain or Open Gate as imperial property. By the World Meridian crisis, imperial power is one participant among several continental institutions rather than the automatic center of the martial world.', members: ['Princess Lucy', 'The Emperor', 'The Empress', 'Imperial Martial Guard'] },
  { id: 'black-mountain', name: 'Black Mountain', category: 'Independent free township and home', alignment: 'Allied', summary: 'Ryn’s remote home grows from one cabin into a free township and later the birthplace of Open Gate. It remains explicitly not Ryn’s kingdom, even while becoming one of the most influential martial locations in the world.', members: ['Ryn', 'Lucy', 'Black Mountain council', 'local families', 'Bracken’s criminal chicken dynasty'] },
  { id: 'azure-dragon-fellowship', name: 'Azure Dragon Fellowship', category: 'Successor relief and coastal-defense network', alignment: 'Allied', summary: 'After Azure Dragon Hall is destroyed in Season 29, survivors refuse to pretend the old institution still exists unchanged. The Fellowship operates across several ports as a mobile coastal-defense, relief, and training network rather than rebuilding one sacred mountain seat.', members: ['Corin Tesh', 'former Azure Dragon disciples', 'coastal rescue teams', 'Han Rook memorial lineage'] },
  { id: 'moonwell-network', name: 'Moonwell Medical Network', category: 'Medical successor network', alignment: 'Allied', summary: 'Jade Moon Sect dissolves in Season 30 rather than surrendering or pretending internal civil fracture never happened. Its clinics and physicians reorganize into a distributed medical network whose techniques are held across multiple custodial archives instead of one sect vault.', members: ['Iseul Venn', 'former Jade Moon physicians', 'regional clinics', 'custodial archives'] },
  { id: 'vagrant-city', name: 'Vagrant City', category: 'Unranked neutral city', alignment: 'Allied', summary: 'A hidden city where powerful masters can refuse Heavenly Register classification. Its existence remains a permanent reminder that official rankings describe public knowledge rather than all strength.', members: ['Fen', 'Grandmother Su', 'Orin', 'Jae', 'City wardens'] },
  { id: 'iron-concord', name: 'Iron Concord Guild', category: 'Arclune No.1 Guild', alignment: 'Mixed', summary: 'The strongest guild of Arclune invades with Banner Legions, linked cultivation doctrine, and military infrastructure rather than a handful of dueling elites. Its eastern war ends when soldiers, War Crowns, and Guildmaster Cyran Vol accept withdrawal terms after Lucy dismantles the political machinery that made Ryn’s direct victory strategically dangerous.', members: ['Cyran Vol', 'Seraph Kade', 'Marek Voss', 'Banner Legions', 'Guild-State councils'] },
  { id: 'varkesh-war-hosts', name: 'Twelve War Hosts of Varkesh', category: 'Northern martial civilization', alignment: 'Mixed', summary: 'Varkesh organizes society through mobile War Hosts rather than sects or guild states. Its apex martial figures earn Throne Names instead of numeric ranks. The World Meridian crisis fractures the Hosts around Kaor Ren’s forced equalization plan without reducing the entire continent to one alignment.', members: ['Tala Vorn', 'Arvek Draal', 'Seyra Khann', 'Orren Vak', 'Maelis Dorn', 'Darr Vesk', 'Iskra Vale', 'Kaor Ren'] },
  { id: 'restoration-mandate', name: 'Restoration Mandate', category: 'Orthodox restoration movement', alignment: 'Mixed', summary: 'A decentralized movement of displaced Orthodox conservatives who believe foreign invasion, sect collapse, Register reform, and Open Gate expansion prove the old order must be restored. Elder Vael Corin becomes its intellectual architect, but cells radicalize beyond his control. The movement fractures after public exposure rather than disappearing neatly.', members: ['Vael Corin', 'displaced Orthodox elders', 'former supply and discipline networks', 'independent radical cells'] },
  { id: 'meridian-compact', name: 'Meridian Compact', category: 'Intercontinental custodial framework', alignment: 'Allied', summary: 'Lucy’s Season 45 answer to both Kaor’s forced equalization and the old unequal status quo. No state, sect, guild, War Host, Register authority, or Open Gate branch may own a World Meridian junction. Local communities receive representation, technical records are public by default, and gradual access programs prioritize medicine, agriculture, and low-density regions over military extraction.', members: ['Eastern governments', 'Varkesh War Hosts', 'Arclune states', 'Nacre representatives', 'Sahraim representatives', 'local community councils', 'independent technical inspectors'] },
  { id: 'six-ancient-houses', name: 'Six Ancient Houses', category: 'Pre-Register martial lineages', alignment: 'Mixed', summary: 'Iron Rain, Red Cedar, Glass Reed, Black River, White Ash, and Stone Veil emerge from centuries of isolation and later reject Mo Yejun’s absolute throne despite internal division.', members: ['House Iron Rain', 'House Red Cedar', 'House Glass Reed', 'House Black River', 'House White Ash', 'House Stone Veil'] },
  { id: 'hollow-heaven', name: 'Hollow Heaven', category: 'Ancient martial compact', alignment: 'Hostile', summary: 'A pre-Pavilion political-martial order that becomes an authoritarian movement under Mo Yejun and is dismantled by Season 15.', members: ['Mo Yejun', 'loyalist house factions', 'hidden cells', 'formation engineers'] },
  { id: 'eclipse-court', name: 'Eclipse Court', category: 'Counter-cultivation order', alignment: 'Hostile', summary: 'A counter-cultivation organization that weaponizes public combat profiles, hostile matchups, predictive data, and the Black Sun Array. Its war kills Kassian Ro and ends when Lucy, Tessan, Ryn, and the Top 20 break the model rather than merely overpowering each counter.', members: ['Aurel Veyr', 'Nine Eclipse Seats', 'Five Crownless Kings', 'formation observers'] },
  { id: 'severed-stars', name: 'Five Severed Stars', category: 'First Silence disciples', alignment: 'Mixed', summary: 'Neris Kaun, Rath Odan, Caldrin Mott, Hessa Dorn, and Varo Kest begin as Yeon Mu-gyeol’s suppressive disciples but eventually make independent choices and help dismantle the Quiet Gate.', members: ['Neris Kaun', 'Rath Odan', 'Caldrin Mott', 'Hessa Dorn', 'Varo Kest'] },
];
