import type { Faction } from './types';

export const factions: Faction[] = [
  { id: 'five-great-orthodox-sects', name: 'Five Great Orthodox Sects', category: 'Orthodox hegemony', alignment: 'Mixed', summary: 'The five institutions that define accepted Orthodox martial law. They begin as Ryn’s hostile institutional enemies but later cooperate with him and Lucy against larger threats without fully resolving their ideological differences.', members: ['Heavenly Sword Palace', 'Nine Suns Monastery', 'Jade Moon Sect', 'Azure Dragon Hall', 'Supreme Dao Sanctuary'] },
  { id: 'celestial-record-pavilion', name: 'Celestial Record Pavilion', category: 'Neutral ranking authority', alignment: 'Allied', summary: 'The organization responsible for the Heavenly Register and Black Register. Repeated crises force it to acknowledge unrecorded masters, preserve historical succession, and eventually supplement rank numbers with capability profiles rather than pretending one number explains every fighter.', members: ['Pavilion Master', 'Register observers', 'Black Register custodians', 'formation analysts including Tessan Ri'] },
  { id: 'imperial-house', name: 'Imperial House', category: 'Royal dynasty', alignment: 'Allied', summary: 'Lucy’s royal family and the political center of the empire. It remains a major political anchor while gradually accepting that Lucy’s marriage to Ryn does not make Black Mountain imperial territory or Ryn a state asset.', members: ['Princess Lucy', 'The Emperor', 'The Empress', 'Imperial Martial Guard'] },
  { id: 'black-mountain', name: 'Black Mountain', category: 'Independent free township and home', alignment: 'Allied', summary: 'Ryn’s remote home grows from a single cabin into a free township of refugees and neighbors. It explicitly refuses to become Ryn’s kingdom, becomes an emergency coordination center when necessary, and hosts Ryn and Lucy’s Season 25 wedding without becoming a royal court.', members: ['Ryn', 'Lucy', 'Black Mountain council', 'Bracken', 'local families'] },
  { id: 'vagrant-city', name: 'Vagrant City', category: 'Unranked neutral city', alignment: 'Allied', summary: 'A hidden city outside sect and royal law where powerful masters can refuse Heavenly Register classification. Vagrant City becomes a crucial intelligence and trade ally for Lucy while preserving its independence.', members: ['Fen', 'Grandmother Su', 'Orin', 'Jae', 'City wardens'] },
  { id: 'six-ancient-houses', name: 'Six Ancient Houses', category: 'Pre-Register martial lineages', alignment: 'Mixed', summary: 'Iron Rain, Red Cedar, Glass Reed, Black River, White Ash, and Stone Veil emerge from centuries of isolation. Their return proves Hollow Heaven is not a single moral bloc: some fight, some defect, and all ultimately reject Mo Yejun’s absolute throne.', members: ['House Iron Rain', 'House Red Cedar', 'House Glass Reed', 'House Black River', 'House White Ash', 'House Stone Veil'] },
  { id: 'hollow-heaven', name: 'Hollow Heaven', category: 'Ancient martial compact', alignment: 'Hostile', summary: 'A pre-Pavilion political-martial order built around powerful lineages beyond public ranking. Under Mo Yejun it becomes an authoritarian movement seeking a world governed by the strongest sovereign and is dismantled by the end of Season 15.', members: ['Mo Yejun', 'loyalist house factions', 'hidden cells', 'formation engineers'] },
  { id: 'black-mountain-coalition', name: 'Black Mountain Coalition', category: 'Temporary multi-faction alliance', alignment: 'Allied', summary: 'Lucy’s emergency coalition of Orthodox sects, unorthodox clans, royal forces, Vagrant City, ranked masters, and defecting ancient houses. Lucy repeatedly refuses attempts to convert emergency cooperation into a permanent government, throne, or empire.', members: ['Lucy', 'Ryn', 'Heavenly Register fighters', 'Vagrant City', 'cooperating Ancient Houses', 'Imperial forces'] },
  { id: 'eclipse-court', name: 'Eclipse Court', category: 'Western counter-cultivation order', alignment: 'Hostile', summary: 'A counter-cultivation organization that studies the public identities of ranked fighters and builds hostile matchups, predictive data, and the Black Sun Array around those assumptions. Its war kills Kassian Ro and ends when Lucy, Tessan, Ryn, and the Top 20 destroy the predictive model.', members: ['Aurel Veyr', 'Nine Eclipse Seats', 'Five Crownless Kings', 'formation observers'] },
  { id: 'severed-stars', name: 'Five Severed Stars', category: 'First Silence disciples', alignment: 'Mixed', summary: 'Neris Kaun, Rath Odan, Caldrin Mott, Hessa Dorn, and Varo Kest are trained by Yeon Mu-gyeol to suppress broad cultivation relationships. Each has a personal grievance rooted in martial abuse. By Season 24 they make independent choices, assist civilian reconstruction, and help dismantle the Quiet Gate rather than remaining anonymous extensions of Mu-gyeol.', members: ['Neris Kaun', 'Rath Odan', 'Caldrin Mott', 'Hessa Dorn', 'Varo Kest'] },
];
