import type { Faction } from './types';

export const factions: Faction[] = [
  { id: 'open-gate', name: 'Open Gate', category: 'Independent intercontinental martial school / sect network', alignment: 'Allied', summary: 'Founded reluctantly by Ryn and Lucy after the Guild War. By S55 Open Gate has four Great Halls, Nine functional Warden seats, Gatekeepers on multiple continents, five active Top-20 members or permanent instructors, restored former Top-Five/Top-Ten masters, and enough institutional depth to perform many protective functions even if the Heavenly Register vanished. Its charter explicitly forbids converting that capability into a right to rule.', members: ['Ryn — Mountain Teacher', 'Lucy — First Steward / Rank #5', 'Mountain Hall', 'Wayfinder Hall', 'Mercy Hall', 'Steward Hall', 'Nine Gate Warden Seats', 'Gatekeepers', 'First Gate', 'Teren Ashval', 'Meira Sun', 'Oris Thane'] },
  { id: 'thousand-lantern-network', name: 'Thousand Lantern Network', category: 'Open Gate intercontinental information network', alignment: 'Allied', summary: 'Built by Lucy, Mira, Ivara, Tessan, Nacre signal experts, Sahraim relays, and Vagrant City couriers. By S55 more than twelve thousand Lantern Nodes transmit priority intelligence across four continents in seconds or minutes. No node holds the full network map, every node can isolate itself, and every message carries source reliability, verification level, time received, independent confirmations, and likely strategic effect. RED GATE is the emergency unknown-threat protocol.', members: ['Lucy', 'Mira Veyl — Warden of the Eye', 'Ivara Pell', 'Tessan Ri', 'regional Gatekeepers', 'Nacre engineers', 'Sahraim relays', 'Vagrant City couriers'] },
  { id: 'celestial-record-pavilion', name: 'Celestial Record Pavilion', category: 'Ranking and capability authority', alignment: 'Allied', summary: 'The Pavilion survives earlier betrayal by exposing records and accepting oversight. The Rank Hunter saga forces it to confront another buried sin: Examiner Zero was once used to test rank accuracy, and politically inconvenient recommendations were sometimes suppressed. After Taewon dies, Veyra becomes #1, Lucy is formally assessed at #5, and Meira Sun returns at #8. The Register remains useful but no longer pretends numeric rank is natural law.', members: ['Register observers', 'Black Register custodians', 'capability analysts', 'public oversight panels'] },
  { id: 'broken-ledger', name: 'Broken Ledger', category: 'Decentralized anti-ranking extremist movement', alignment: 'Hostile', summary: 'A leaderless collection of failed challengers, aggrieved cultivators, opportunists, and extremists inspired by Kaiven Rhoss even though he never successfully controls them. Their replica broken tokens turn the Rank Hunter’s critique into indiscriminate violence. They attack Lantern nodes, ranked institutions, and Open Gate branches before fracturing under S55 counter-operations.', members: ['independent cells', 'failed Pavilion candidates', 'anti-Register radicals', 'criminal imitators'] },
  { id: 'meridian-compact', name: 'Meridian Compact', category: 'Intercontinental custodial framework', alignment: 'Allied', summary: 'Lucy’s answer to Kaor’s forced equalization and the old unequal status quo. No state, sect, guild, War Host, Register authority, or Open Gate branch may own a World Meridian junction. The Thousand Lantern Network later uses Compact monitoring points to detect Kaiven’s attempt to externalize Hundred Graves into the Meridian.', members: ['Eastern governments', 'Varkesh War Hosts', 'Arclune states', 'Nacre representatives', 'Sahraim representatives', 'local community councils', 'independent technical inspectors'] },
  { id: 'five-great-orthodox-sects', name: 'Five Great Orthodox Sects', category: 'Former Orthodox hegemony', alignment: 'Mixed', summary: 'Historically Heavenly Sword Palace, Nine Suns Monastery, Jade Moon Sect, Azure Dragon Hall, and Supreme Dao Sanctuary. Azure Dragon falls physically and Jade Moon dissolves; the remaining old sects coexist uneasily with Open Gate and successor networks.', members: ['Heavenly Sword Palace', 'Nine Suns Monastery', 'Supreme Dao Sanctuary', 'Azure Dragon Fellowship', 'Moonwell Medical Network'] },
  { id: 'black-mountain', name: 'Black Mountain', category: 'Independent free township and Open Gate birthplace', alignment: 'Allied', summary: 'Ryn and Lucy’s home becomes the training and emotional center of Open Gate without becoming a kingdom. By S55 Ryn’s Spring aura can extend across much of the mountain and continuously improves recovery and cultivation quality for people training within it.', members: ['Ryn', 'Lucy', 'Black Mountain council', 'Open Gate students', 'local families', 'Bracken’s criminal chicken dynasty'] },
  { id: 'azure-dragon-fellowship', name: 'Azure Dragon Fellowship', category: 'Successor relief and coastal-defense network', alignment: 'Allied', summary: 'Survivors of the destroyed Azure Dragon Hall operate across ports rather than pretending the old sacred seat still exists.', members: ['Corin Tesh', 'former Azure Dragon disciples', 'coastal rescue teams'] },
  { id: 'moonwell-network', name: 'Moonwell Medical Network', category: 'Medical successor network', alignment: 'Allied', summary: 'Jade Moon clinics reorganize into a distributed medical system after the sect’s dissolution. It works closely with Open Gate Mercy Hall and Iseul Venn.', members: ['Iseul Venn', 'former Jade Moon physicians', 'regional clinics', 'custodial archives'] },
  { id: 'vagrant-city', name: 'Vagrant City', category: 'Unranked neutral city', alignment: 'Allied', summary: 'A city where powerful masters may refuse public ranking. Its intelligence couriers later become one of the physical redundancy layers beneath the Thousand Lantern Network.', members: ['Fen', 'Grandmother Su', 'Orin', 'Jae', 'City wardens'] },
  { id: 'iron-concord', name: 'Iron Concord Guild', category: 'Arclune No.1 Guild', alignment: 'Mixed', summary: 'The former invading No.1 Guild of Arclune survives its failed war and internal reforms. Veteran signal and logistics specialists later cooperate with intercontinental Open Gate infrastructure without controlling it.', members: ['Cyran Vol', 'Seraph Kade', 'Marek Voss', 'Banner veterans', 'Guild-State councils'] },
  { id: 'varkesh-war-hosts', name: 'Twelve War Hosts of Varkesh', category: 'Northern martial civilization', alignment: 'Mixed', summary: 'Varkesh organizes around mobile War Hosts and Throne Names rather than numeric ranks. Several Varkesh communities host early foreign Open Gate branches and Lantern relays.', members: ['Tala Vorn', 'Arvek Draal', 'Seyra Khann', 'Orren Vak', 'Maelis Dorn', 'Darr Vesk', 'Iskra Vale'] },
  { id: 'restoration-mandate', name: 'Restoration Mandate', category: 'Orthodox restoration movement', alignment: 'Mixed', summary: 'A decentralized conservative movement that fractures after trying to force the old Orthodox order back into place. Its aftermath helps motivate Open Gate’s transparent tribunal and intelligence safeguards.', members: ['Vael Corin', 'displaced Orthodox elders', 'former supply networks', 'independent radical cells'] },
  { id: 'six-ancient-houses', name: 'Six Ancient Houses', category: 'Pre-Register martial lineages', alignment: 'Mixed', summary: 'Iron Rain, Red Cedar, Glass Reed, Black River, White Ash, and Stone Veil emerge from isolation and later reject Mo Yejun’s absolute throne.', members: ['House Iron Rain', 'House Red Cedar', 'House Glass Reed', 'House Black River', 'House White Ash', 'House Stone Veil'] },
  { id: 'hollow-heaven', name: 'Hollow Heaven', category: 'Ancient martial compact', alignment: 'Hostile', summary: 'A pre-Pavilion political-martial order that becomes authoritarian under Mo Yejun and is dismantled by S15.', members: ['Mo Yejun', 'loyalist house factions', 'hidden cells'] },
  { id: 'eclipse-court', name: 'Eclipse Court', category: 'Counter-cultivation order', alignment: 'Hostile', summary: 'A counter-cultivation organization that weaponizes public combat profiles and predictive data. Its collapse helps inspire later emphasis on adaptability and information accountability.', members: ['Aurel Veyr', 'Nine Eclipse Seats', 'Five Crownless Kings'] },
  { id: 'severed-stars', name: 'Five Severed Stars', category: 'First Silence disciples', alignment: 'Mixed', summary: 'Mu-gyeol’s former suppressive disciples eventually make independent choices and help dismantle the Quiet Gate.', members: ['Neris Kaun', 'Rath Odan', 'Caldrin Mott', 'Hessa Dorn', 'Varo Kest'] },
];
